apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: employee-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
    - name: run-image
      value: gcr.io/taaron-1/employee-app
  source:
    git:
      url: https://github.com/garreeoke/employee-app
      ref:
        branch: main
